INSERT into Department (department_id,name) values ('CS','Department of Computer Science and Engineering');
INSERT into Department (department_id,name) values ('EE','Department of Electronics and Electrical Engineering');
INSERT into Department (department_id,name) values ('ME','Department Of Mechanical Engineering');
INSERT into Department (department_id,name) values ('CE','Department of Civil Engineering');
INSERT into Department (department_id,name) values ('BT','Department Of Biosciences and Bioengineering');
INSERT into Department (department_id,name) values ('CL','Department Of Chemical Engineering');
INSERT into Department (department_id,name) values ('PH','Department Of Physics');
INSERT into Department (department_id,name) values ('CH','Department Of Chemical Sciences and Technology');
INSERT into Department (department_id,name) values ('MA','Department Of Mathematics and Computing');
INSERT into Department (department_id,name) values ('HS','Department Of Humanities and Social Sciences');
INSERT into Department (department_id,name) values ('RT','Centre for Rural Technology');
INSERT into Department (department_id,name) values ('EN','Center for Energy');
INSERT into Department (department_id,name) values ('LS','Centre for Linguistic Science and Technology');
